### PR TITLE
Fixed specs and slug for multi-language

### PR DESCRIPTION
**Pull request by matjack1**
Hi,
in the first commit I've fixed the specs with the new Globalize gem.
In the second commit I've added the possibility to create a translated object with all translations in one single step. This is useful to integrate with ActiveAdmin (though it's not tested directly with that).
I've tested the new feature. Let me know if you need any explaination. Cheers!

### CODE REVIEW

**Comment by mvdstam** [comment]
Please merge this and roll out as a release. Works really well. :+1:

**Comment by parndt** [comment]
Yep, merged it.. but the tests aren't passing.

**Comment by mvdstam** [comment]
That's strange; I saw a Travis CI box just before the merge here which said all was okay.

**Comment by mvdstam** [comment]
I think I know where this is going wrong. Try updating your gemspec to use Friendly ID 5.1.0.beta.1 instead of the older beta you're using now. Also, I'm using Globalize ~> 4.0.2 here as well. That combination of gems seem to work without any problems here.

**Comment by parndt** [comment]
Hmm, doesn't seem to have fixed it..

**Comment by matjack1** [comment]
I can take a look again at this by the end of the week

**Comment by mvdstam** [comment]
I've done some further checking, and this definitely seems to be a problem with Globalize. Switching to the rails-4-2-upgrade branch of Globalize results in all tests passing.

**Comment by parndt** [comment]
Confirm, I've switched it to that for now.

**Comment by mvdstam** [comment]
Perhaps this is a good moment to consider merging the rails-4-2-upgrade branch back into master as well, @parndt, or is it too early for that?

**Comment by parndt** [comment]
too early, not all the tests are passing yet.

**Comment by mvdstam** [comment]
Alright then, I'll see if I can contribute in any way to make that happen. Thanks @parndt!

**Comment by parndt** [comment]
Thank you all!

**Pull request merged**
