### PR TITLE
Add history support

### PR DESCRIPTION
**Pull request by sasselin**
Add generator to create migration and overwrite base history to support multi-language

### CODE REVIEW

**Comment by gabriel-cardoso** [comment]
:+1:

**Comment by florianeck** [comment]
why is this not merged? not having the history makes the gem kinda useless

**Comment by sasselin** [comment]
I don't know :(

**Comment by fconforti** [comment]
Any chance to have this merged?

**Comment by h8rry** [comment]
Can we merge this? Or reflect on the documentation?

**Comment by seanfcarroll** [comment]
Would be great to be merged

**Comment by sasselin** [comment]
I think the gem has been abandoned :(

**Comment by florianeck** [comment]
@sasselin what makes you think so? if this is the case, maybe somebody wants to take over the owernership?

**Comment by kevin-jj** [comment]
@parndt @norman  Would be great to be merged and compatible with friendly_id 5.2.0

**Comment by parndt** [comment]
Wow, I never got notified of this!

**Pull request merged**
