### PR TITLE
Fixed Rails 5.2 plain SQL order warning

### LINKED ISSUE #25: Rails 5.2 warnings
I am getting a lot of these warnings, after I upgraded a project to Rails 5.2.

```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "\"friendly_id_slugs\".id DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from super_create_slug at /home/dev/.rvm/gems/ruby-2.4.4/bundler/gems/friendly_id-globalize-b5c1b8b442f6/lib/friendly_id/history.rb:130)
```

### PR DESCRIPTION
**Pull request by kaspernj**
Closes #25

### CODE REVIEW

**Comment by kaspernj** [comment]
Any news here? :-)

**Comment by OleksandrPoltavets** [comment]
When this fix can be merged to master?

**Comment by beneggett** [comment]
Bump for visibility

**Comment by teohm** [comment]
@norman Need any help from us to merge and release this PR?

**Comment by kevin-jj** [comment]
> @norman Need any help from us to merge and release this PR?

cc @parndt

**Comment by parndt** [comment]
Thanks for the mention @kevin-jj 👍

**Pull request merged**
